### ISSUE TITLE
手机端 Markdown 编辑器

### ISSUE THREAD

**Issue by xcatliu** [open-ideas-club/ideas#12]
- 支持手机端编辑
- 一些常用按键（比如 `-`, `*`, `#`, <code>`</code>）作为功能键给出
- 支持分享到剪贴板，邮件等地方

**Comment by xcatliu** [comment]
找了下，已有竞品：[Drafts](https://itunes.apple.com/us/app/drafts-4-quickly-capture-notes/id905337691?mt=8)
貌似评价不错

**Comment by xcatliu** [comment]
已下载，完美满足所有需求

**Comment by rakernel** [comment]
iPhone还有比较好的就是IA Writer，Android也推出了。也拥有实体键盘快捷键，还有focus模式比较赞

**Comment by xcatliu** [comment]
@rakernel 多谢分享，我去尝试下~
